# Wykład 5: od generatora do półgrupy {-}

2024-10-31

*Piotr Dyszewski*


## O notacji słów kilka {-}

::: {.theorem}
Przy oznaczeniach Twierdzenia \@\ref{thm:3-16}, dla $f \in C_0(S)$ oraz $t > 0$,
$$
\lim_{n \to \infty} \left(I - \frac{t}{n} L\right)^{-n} f = T_tf.
$$
:::

::: {.proof}
Sprawdzamy indukcyjnie, że
$$
\left(I - \alpha^{-1} L\right)^{-n} f
= \alpha^n U^n(\alpha)f
= \int_0^{\infty} \alpha^n s^{n-1} e^{-\alpha s} T(s)f \, \mathrm{d}s.
$$
Stąd
\begin{equation}
\left( I - \frac{t}{n} L \right)^{-n} f
= \mathbb{E} T \left( (\xi_1 + \cdots + \xi_n) t/n \right) f, 
(\#eq:3-18)
\end{equation}
gdzie $\xi_1, \xi_2, \ldots$ są niezależnymi zmiennymi
o standardowym rozkładzie wykładniczym.
Zauważmy, że funkcja $(s, x) \to T(s)f(x)$ jest ciągła,
więc wartość oczekiwana w \@ref(eq:3-18) jest dobrze określona.

Jeśli $f \in \mathcal{D}(L)$, to
\begin{equation*}
	\frac{\mathrm{d}}{\mathrm{d}t} T_t f = T_t Lf
\end{equation*}
co w notacji całkowej zapisuje się jako
\begin{equation*}
	T_tf-T_sf = \int_s^t T_r Lf \mathrm{d}r.
\end{equation*}
Skoro $\|T_r \| \leq 1$, to ostatnia nierówność implikuje, że
$$
\| T(t)f - T(s)f \| \leq \| Lf \| |t - s|.
$$
Wracając teraz do \@ref(eq:3-18) otrzymujemy
$$
\left\| \left( I - \frac{t}{n} L \right)^{-n} f - T(t)f \right\|
\leq t \| Lf \| \mathbb{E} \left| \frac{\xi_1 + \cdots + \xi_n}{n} - 1 \right|.
$$
Rezultat dla $f \in \mathcal{D}(L)$ wynika teraz z prawa wielkich liczb.
Jest on prawdziwy dla wszystkich $f \in C_0(S)$,
ponieważ wszystkie  rozważane operatory są kontrakcjami.
:::
::: {.remark #uw-3-17}
Formalnie, $T_t = \exp(tL)$. 
Kiedy $L$ jest ograniczone, istnieją przynajmniej trzy sposoby definiowania tego wykładnika:
$$
\sum_{k=0}^\infty \frac{(tL)^k}{k!}, \quad 
\lim_{n \to \infty} \left(I + \frac{t}{n} L\right)^n, 
\quad \text{ i } \quad \lim_{n \to \infty} \left(I - \frac{t}{n} L\right)^{-n}.
$$
Ostatni z nich jest jedynym, który ma sens w przypadku nieograniczonym.
:::

Teraz rozważmy kilka przykładów.

::: {.exercise #ex-3-18}
Rozważmy proces Fellera polegający na jednostajnym ruchu w prawo. 
Niech $S=\mathbb{R}$ i niech $\mathbf{P}_x$ jest punktową 
masą na ścieżce $\omega_x$ danej przez $\omega_x(t) = x + t$, 
lub równoważnie, proces z półgrupą 
$T(t)f(x) = f(x + t)$. 
Pokaż, że generatorem $L$ tego procesu jest 
ten opisany w Zadaniu~\ref{zad:3:13}.
Upewnij się, że dziedzina dana jest dokładnie przez dziedzinę $L$.
:::
::: {.example #3-brown}
W przypadku ruchu Browna, można zweryfikować, że
$$
U(\lambda) f(x) = \int u_\lambda(y - x) f(y) \, dy
$$
gdzie
$$
u_\lambda(y - x) = 
\int_0^\infty (2 \pi t)^{-1/2} \exp\left(-\frac{|y - x|^2}{2t} - \lambda t\right) \, \mathrm{d}t 
= \frac{1}{\sqrt{2 \lambda}} \exp(-|y - x| \sqrt{2 \lambda}).
$$
Elegancki sposób na uzyskanie tej ostatniej równości polega na użyciu wzoru 
$\mathbb{E}[e^{-\lambda T_a}] = e^{-a \sqrt{2 \lambda}}$ dla transformaty Laplace'a 
czasu trafienia $a > 0$ przez rzeczywisty ruch Browna rozpoczęty z $0$. 
Różniczkując względem $\lambda$, 
otrzymujemy 
$$
\mathbb{E}\left[T_a e^{-\lambda T_a}\right] = \frac{a}{\sqrt{2 \lambda}} e^{-a \sqrt{2 \lambda}},
$$
i używając gęstości $T_a$, aby przekształcić $\mathbb{E}[T_a e^{-\lambda T_a}]$, 
dokładnie znajdujemy całkę, która pojawia się w obliczeniach $u_\lambda(y - x)$. 

Wiemy, że półgrupa operatorów związana z ruchem Browna jest półgrupą Fellera. 
Znajdziemy jej generator $L$. 
Widzieliśmy, że dla każdego $\lambda > 0$ i $f \in C_0(\mathbb{R})$,
$$
U(\lambda) f(x) = 
\int \frac{1}{\sqrt{2 \lambda}} \exp(-\sqrt{2 \lambda} |y - x|) f(y) \, \mathrm{d}y.
$$
Jeśli $h \in \mathcal{D}(L)$, 
wiemy, że istnieje $f \in C_0(\mathbb{R})$ takie, 
że $h = U(\lambda) f$. 
Przyjmując $\lambda = 1/2$, mamy
$$
h(x) = \int \exp(-|y - x|) f(y) \, \mathrm{d}y.
$$
Różniczkując pod znakiem całki (pozostawiamy uzasadnienie jako zadanie), 
otrzymujemy, że $h$ jest różniczkowalna na $\mathbb{R}$, i
$$
h'(x) = \int \operatorname{sgn}(y - x) \exp(-|y - x|) f(y) \, \mathrm{d}y
$$
gdzie $\operatorname{sgn}(z) = 1_{\{z > 0\}} - 1_{\{z < 0\}}$ 
(wartość $\operatorname{sgn}(0)$ jest nieistotna). 
Pokażmy również, że $h'$ jest różniczkowalna na $\mathbb{R}$. 
Niech $x_0 \in \mathbb{R}$. 
Następnie, dla $x > x_0$,
\begin{align*}
h'(x) - h'(x_0)  = & 
\int_{\mathbb{R}} \left( \operatorname{sgn}(y - x) \exp(-|y - x|) - 
\operatorname{sgn}(y - x_0) \exp(-|y - x_0|) \right) f(y) \, \mathrm{d}y \\
=&  \int_{x_0}^x \left( -\exp(-|y - x|) - \exp(-|y - x_0|) \right) f(y) \, \mathrm{d}y \\
&+ \int_{\mathbb{R} \setminus [x_0, x]} \operatorname{sgn}(y - x_0) 
\left( \exp(-|y - x|) - \exp(-|y - x_0|) \right) f(y) \, \mathrm{d}y.
\end{align*}
Wynika stąd, że
$$
\frac{h'(x) - h'(x_0)}{x - x_0} 
\xrightarrow{x \downarrow x_0} -2f(x_0) + h(x_0).
$$
Otrzymujemy tę samą granicę, gdy $x \uparrow x_0$, 
i stąd uzyskujemy, że $h$ jest dwukrotnie różniczkowalna oraz $h'' = -2f + h$.

Z drugiej strony, ponieważ $h = U(1/2)f$,
$$
\left(\frac{1}{2} - L\right) h = f
$$
stąd $Lh = -f + h/2 = h''/2$.
Podsumowując, uzyskaliśmy, że
$$
\mathcal{D}(L) \subset \{ h \in C^2(\mathbb{R}) : h \text{ i } h'' \in C_0(\mathbb{R}) \}
$$
i że, jeśli $h \in \mathcal{D}(L)$, mamy $Lh = h''/2$.

Ostatnie zawieranie jest w rzeczywistości równością. 
Aby to zobaczyć, możemy postąpić następująco. 
Jeśli $g$ jest funkcją dwukrotnie różniczkowalną taką, że $g$ oraz $g''$ należą do $C_0(\mathbb{R})$, 
wtedy przyjmujemy $f = \frac{1}{2}(g - g'') \in C_0(\mathbb{R})$, 
a więc $h = U(1/2)f \in \mathcal{D}(L)$. 
Z poprzedniego argumentu wynika, 
że $h$ jest dwukrotnie różniczkowalna oraz $h'' = -2f + h$. 
Stąd $(h - g)'' = h - g$. 
Ponieważ funkcja $h - g$ należy do $C_0(\mathbb{R})$, 
musi zanikać tożsamościowo, co daje $g = h \in \mathcal{D}(L)$.
:::
Patrząc na Zadanie \@ref(exr:3-13) i Przykład \@ref(exm:3-brown),
można by się zastanawiać, czy pochodne wyższego rzędu mogą 
być generatorami infinitezymalnymi. Odpowiedź brzmi, że nie mogą. 
Główny problem polega na tym, 
że gdy gładka funkcja osiąga minimum w punkcie wewnętrznym swojej dziedziny, 
pierwsza pochodna jest zerowa, 
a druga pochodna jest tam nieujemna. 
Nic nie można powiedzieć o znakach innych pochodnych w tym miejscu.

::: {.exercise #3-21}
Pokaż, że nie istnieje generator prawdopodobieństwa, 
którego ograniczenie do gładkich funkcji jest dane przez \(Lf = f'''\).
:::

## Od generatora do procesu {-}

W całym tym rozdziale \(L\) będzie generatorem infinitezymalnym.
Naszym pierwszym zadaniem jest skonstruowanie odpowiadającej półgrupy prawdopodobieństwa.
Aby to zrobić, wprowadzamy aproksymację \(L_\epsilon\) do \(L\) dla małego dodatniego \(\epsilon\) przez
$$
L_\epsilon = L(I - \epsilon L)^{-1}.
$$
Zauważmy, że jest to dobrze zdefiniowane z definicji generatora infinitezymalnego,
ponieważ \(\mathcal{R}(I - \epsilon L) = \mathcal{D}(L)\). To łatwo zobaczyć z
$$
f - \epsilon L f = g \quad
\text{jest równoważne} \quad
f = (I - \epsilon L)^{-1} g.
$$
Ponadto
$$
\|L_\epsilon g\|
= \|L f\| \leq \frac{\|f\| + \|g\|}{\epsilon}
\leq \frac{2}{\epsilon} \|g\|,
$$
więc \(L_\epsilon\) jest ograniczonym operatorem.
To pozwala zdefiniować \(T_\epsilon(t)\) przez
$$
T_\epsilon(t)
= e^{tL_\epsilon}
= \sum_{n=0}^{\infty} \frac{t^n L_\epsilon^n}{n!}.
$$

::: {.exercise #zad-3-23}
- **(a)** Pokaż, że dla każdego \(f \in C_0(S)\),
  \begin{equation}
  (I - \epsilon L)^{-1} f - \epsilon L f = f.
(\#eq:3-19)
  \end{equation}
- **(b)** Użyj części (a), aby pokazać, że \(L_\epsilon\) jest generatorem infinitezymalnym
  oraz że \(T_\epsilon(t)\) jest półgrupą prawdopodobieństwa, 
  której generatorem jest \(L_\epsilon\) w sensie Twierdzenia \@ref(thm:3-16).
:::

::: {.theorem #3-24}
Dla \(f \in C_0(S)\),
$$
T(t)f = \lim_{\epsilon \to 0} T_\epsilon(t) f
$$
jednostajnie na ograniczonych przedziałach \(t\).
Definiuje to półgrupę Fellera, której generatorem jest \(L\) w sensie Twierdzenia \@ref(thm:3-16).
:::

Najpierw sprawdzamy, że \(L_\epsilon\) i \(L_\delta\) komutują dla \(\epsilon, \delta > 0\).
Wynika to z \@ref{eq:3-19} oraz
$$
(I - \epsilon L)^{-1} (I - \delta L)^{-1}
= (I - \delta L)^{-1} (I - \epsilon L)^{-1},
$$
co jest prawdziwe, ponieważ
$$
(I - \epsilon L)^{-1} (I - \delta L)^{-1} f
= g
\quad \text{jest równoważne}
\quad f
= g - (\epsilon + \delta)Lg + \epsilon \delta L^2 g,
$$
co jest symetryczne w \(\epsilon\) i \(\delta\).


